export default [
  { id: 1, title: 'Inception', genre: 'Science Fiction' },
  { id: 2, title: 'The Matrix', genre: 'Action' },
  { id: 3, title: 'Interstellar', genre: 'Adventure' },
  { id: 4, title: 'The Dark Knight', genre: 'Crime' },
  { id: 5, title: 'Titanic', genre: 'Romance' },
  { id: 6, title: 'Avengers: Endgame', genre: 'Superhero' },
  { id: 7, title: 'Parasite', genre: 'Thriller' },
  { id: 8, title: 'The Godfather', genre: 'Drama' },
  { id: 9, title: 'The Shawshank Redemption', genre: 'Drama' },
  { id: 10, title: 'Pulp Fiction', genre: 'Crime' },
  { id: 11, title: 'The Lion King', genre: 'Animation' },
  {
    id: 12,
    title: 'The Lord of the Rings: The Return of the King',
    genre: 'Fantasy',
  },
  { id: 13, title: 'Frozen', genre: 'Animation' },
  { id: 14, title: 'Joker', genre: 'Psychological Thriller' },
  { id: 15, title: 'Forrest Gump', genre: 'Comedy-Drama' },
];
